<?php
/** @var \YellowCard\JsBasic\ViewModel\Message $messageViewModel */
$messageViewModel = $block->getData('message_view_model');
?>

<div id="vue-test">
    <h1>{{ message }}</h1>
</div>

<script type="text/x-magento-init">
    {
        "#vue-test": {
            "YellowCard_JsBasic/js/vue-test": {
                "message": "<?= $messageViewModel->getMessage() ?>"
            }
        }
    }
</script>
